var bBrowser,MAKO_POPUPBLOCKED="Please disable all popup blockers.";if(document.ELEMENT_NODE==null){document.ELEMENT_NODE=1;document.TEXT_NODE=3}
addLoadEvent(function(){fieldFocus();if(!_gel('__aspnetForm')||!_gel('__aspnetForm').__SCROLLPOS)return false;var o=_gel('bViewport');if(!o){window.onscroll=function(){var y=window.pageYOffset;y=(y)?y:document.body.parentNode.scrollTop;_gel('__aspnetForm').__SCROLLPOS.value=y;};if(window.pageY){window.pageY=_gel('__aspnetForm').__SCROLLPOS.value;}else{document.body.parentNode.scrollTop=_gel('__aspnetForm').__SCROLLPOS.value;}}else{o.onscroll=function(){_gel('__aspnetForm').__SCROLLPOS.value=o.scrollTop;};o.scrollTop=_gel('__aspnetForm').__SCROLLPOS.value;}})
addLoadEvent(function(){var l=document.location,b=_gelstn('base'),e=_gelstn('a');if(b.length>0){for(var i=0;i<e.length;i++){if(e[i].href){var a=e[i],h=a.hash;if(h.length>0&&a.href.indexOf(b[0].href)>-1){a.href=l;a.hash=h;}}}}})
addUnloadEvent(function(){if(help&&!help.closed){help.getNewReferrance()}})
function addLoadEvent(f){var o=window.onload;(typeof o!='function')?window.onload=f:(window.onload=function(e){o(e);f(e);});}
function addUnloadEvent(f){var o=window.onunload;(typeof o!='function')?window.onunload=f:(window.onunload=function(e){o(e);f(e);});}
function addFocusEvent(f,c){if(!c)c=document;var o=c.onfocus;(typeof o!='function')?c.onfocus=f:(c.onfocus=function(e){o(e);f(e);});}
function addBlurEvent(f,c){if(!c)c=document;var o=c.onblur;(typeof o!='function')?c.onblur=f:(c.onblur=function(e){o(e);f(e);});}
function addMouseMoveEvent(f,c){if(!c)c=document.body;var o=c.onmousemove;(typeof o!='function')?c.onmousemove=f:(c.onmousemove=function(e){o(e);f(e);});}
function addResizeEvent(f){var o=window.onresize;(typeof o!='function')?window.onresize=f:(window.onresize=function(e){o(e);f(e);});}
function addKeyDownEvent(f,c){if(!c)c=document;var o=c.onkeydown;(typeof o!='function')?c.onkeydown=f:(c.onkeydown=function(e){o(e);f(e);});}
function addKeyUpEvent(f,c){if(!c)c=document;var o=c.onkeyup;(typeof o!='function')?c.onkeyup=f:(c.onkeyup=function(e){o(e);f(e);});}
function lazyLoad(url,callback,func,ctx){if(!ctx)ctx=window;var id,m,r=new RegExp("[^/]*?([a-z]+[0-9a-z]*)(\\.+[a-z0-9]+)+$","i");if(m=r.exec(url))id=m[1]+'_script';if(typeof ctx[id]!="undefined"){if(ctx[id].loaded==true)callback();else{var f=ctx[id].exec;ctx[id].exec=function(){f();callback()}}}else if(typeof ctx[func]=="undefined"){var el=ctx.document.createElement('script');el.setAttribute("type","text/javascript");el.setAttribute("src",url);if(typeof el!="undefined")ctx.document.getElementsByTagName("head")[0].appendChild(el);ctx[id]=new Object();ctx[id].t=0;ctx[id].exec=function(){if(ctx[id].t>20)return;else ctx[id].t++;if(typeof ctx[func]=="undefined")ctx[id].to=ctx.setTimeout("window['"+id+"'].exec()",200);else{callback();ctx[id].loaded=true;}};ctx[id].exec();}}
function openDialog(path,w,h,n,options,lp){if(!w){w=450};if(!h){h=450};if(!n){n='popup'};var url=path,l=((screen.availWidth-w)/2),t=((screen.availHeight-h)/2);if(path.indexOf("://")==-1)url=oBase+path;if(options){options+=",";}else{options="scrollbars,";};var win=window.open(url,n,options+"width="+w+",height="+h+",left="+l+",top="+t);if(win){win.focus();}else{alert(MAKO_POPUPBLOCKED);return;};win.lp=lp;window.lp=lp;window.popup=win;window.onfocus=function(){if(window.popup&&!window.popup.closed)window.popup.focus();else window.popup=null;};}
var help=null;function openDynHelp(type,root,topic,anchor){if(this.dhType!=type||this.dhRoot!=root||this.dhTopic!=topic){this.dhType=type;this.dhRoot=root;this.dhTopic=topic;if(this.dynhelp){this.dynhelp.document.open("text/html");var response=HelpSystemAjaxFunctions.GetDynHelp(type,root,topic);this.dynhelp.document.writeln(response.value);this.dynhelp.document.close();}}}
function openHelp(type,root,topic,anchor){var path=oBase+"/system/sysapps/help/";if(!anchor)anchor='top';if(help&&help.open&&!help.closed){help.mainFrame.location=path+"helpTopic.aspx?type="+type+"&root="+root+"&topic="+topic+"#"+anchor;}else{help=window.open(path+"helpframe.aspx?type="+type+"&root="+root+"&topic="+topic+"_"+anchor,"help","status,resizable,width=250,scrollbars,left="+screen.availWidth);if(!help){alert('Please disable popup blockers');}else{HelpWin();}}}var oh,ow,ol,ot,mh,sh,lc,rc,ocw,och,ocl,oct,mcw,mch,mcl,mct,swidth,sheight;function HelpWin(){ocw=(window.innerWidth)?window.innerWidth:document.body.offsetWidth;och=(window.innerHeight)?window.innerHeight:document.body.offsetHeight;ocl=(window.screenLeft)?window.screenLeft:window.screenX;oct=(window.screenTop)?window.screenTop:window.screenY;sheight=screen.availHeight;swidth=screen.availWidth;window.resizeTo(swidth,sheight);window.moveTo(0,0);mcw=(window.innerWidth)?window.innerWidth:document.body.offsetWidth;mch=(window.innerHeight)?window.innerHeight:document.body.offsetHeight;mcl=(window.screenLeft)?window.screenLeft:window.screenX;mct=(window.screenTop)?window.screenTop:window.screenY;mh=mct;sh=sheight-mh-mch;lc=mcl;rc=swidth-lc-mcw;ol=ocl-lc;ot=oct-mh;oh=((sheight-mch)+och);ow=((swidth-mcw)+ocw);window.resizeTo(ow-250,oh);window.moveTo(ol,ot);if(help&&!help.closed){help.resizeTo(250,oh);help.moveTo(ol+ow-250,ot);help.focus();help.ow=ow;help.oh=oh;}}
var focusField;function fieldFocus(){if(focusField){try{_gel(focusField).focus();}catch(e){window.setTimeout("fieldFocus();",1000);}}}
function _gel(a){return document.getElementById?document.getElementById(a):null}
function _gelstn(a){return document.getElementsByTagName?document.getElementsByTagName(a):new Array()}
function _ce(t){return window.document.createElement(t)}
function helpClosed(w,h){ow=w;oh=h;setTimeout('((help)?help.closed:true)?window.resizeTo('+w+','+h+'):"";',500);}
function AddToFavorites(t,u){window.external.addFavorite(u||window.location.href,t||window.document.title);return true;}
function browserType() {if (bBrowser === undefined) {var agt = navigator.userAgent.toLowerCase();if (agt.toLowerCase().indexOf('konqueror') != -1) {bBrowser = 'kq';} else if (agt.toLowerCase().indexOf('opera') != -1){bBrowser = 'op';} else if (agt.toLowerCase().indexOf('netscape') != -1){bBrowser = 'ns';}else if(agt.toLowerCase().indexOf('msie')!=-1){bBrowser='ie';}else if(agt.toLowerCase().indexOf('safari')!=-1) {bBrowser = 'safari';}if(bBrowser===undefined) {bBrowser = 'mo';}}return bBrowser;}
function browserVersion(){var sType=browserType();var iVersion=parseFloat(navigator.appVersion);var sAgent=navigator.userAgent.toLowerCase();if(sType=='ie'){var temp=navigator.appVersion.split("MSIE");iVersion=parseFloat(temp[1]);}if(sType=='ns'){var temp=sAgent.split("netscape");if(temp[1]){iVersion=parseFloat(temp[1].split("/")[1]);}}if(sType=='mo'){var temp=sAgent.split("firefox");if(!temp[1]){temp=sAgent.split("trident");}if(temp[1]){iVersion=parseFloat(temp[1].split("/")[1]);}}return iVersion;}
function createCookie(name,value,days){if(days){var date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));var expires=";expires="+date.toGMTString();}else var expires="";document.cookie=name+"="+value+expires+"; path=/";}
function readCookie(name){var nameEQ=name+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' ')c=c.substring(1,c.length);if(c.indexOf(nameEQ)==0)return c.substring(nameEQ.length,c.length);}return null;}
function eraseCookie(name){createCookie(name,"",-1);}
function getParam(name){var m,p=new Object(),r=new RegExp("[\?&]([^&=]+)=([^&=]+)","gi");while(m=r.exec(window.location))p[m[1]]=m[2];return name?p[name]:p;}
function replaceIEPngs(){if(browserType()=='ie'){if(browserVersion()==5.5||browserVersion()==6){rpng(_gelstn("IMG"));rpng(_gelstn("TABLE"));rpng(_gelstn("TD"));rpng(_gelstn("TR"));rpng(_gelstn("DIV"));rpng(_gelstn("SPAN"));function rpng(objs){for(var i=0;i<objs.length;i++){if(objs[i].src){var s=objs[i].src;if(ipng(s)){objs[i].style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+s+"', sizingMethod='scale')";objs[i].src=oBase+"/system/resources/images/spacer.gif";}}else if(objs[i].currentStyle["backgroundImage"]!="none"){var m=/url\("(.*)"\)/i.exec(objs[i].currentStyle["backgroundImage"]);var s=(m)?m[1]:"";if(ipng(s)){objs[i].style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+s+"', sizingMethod='scale')";objs[i].style.backgroundImage="url()";}}}}function ipng(p){return(p.substring(p.length-3,p.length).toUpperCase()=="PNG")}}}}
function findPos(obj){var curleft=curtop=0;if(obj.offsetParent){curleft=obj.offsetLeft;curtop=obj.offsetTop;while(obj=obj.offsetParent){if(obj.id=="bCanvas")break;curleft+=obj.offsetLeft;curtop+=obj.offsetTop;}}return{left:curleft,top:curtop};}
function MM_preloadImages(){var d=document;if(d.images){if(!d.MM_p)d.MM_p=new Array();var i,j=d.MM_p.length,a=MM_preloadImages.arguments;for(i=0;i<a.length;i++)if(a[i].indexOf("#")!=0){d.MM_p[j]=new Image;d.MM_p[j++].src=a[i];}}}
function MM_swapImgRestore(){var i,x,a=document.MM_sr;for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++)x.src=x.oSrc;}
function MM_findObj(n,d){var p,i,x;if(!d)d=document;if((p=n.indexOf("?"))>0&&parent.frames.length){d=parent.frames[n.substring(p+1)].document;n=n.substring(0,p);}if(!(x=d[n])&&d.all)x=d.all[n];for(i=0;!x&&i<d.forms.length;i++)x=d.forms[i][n];for(i=0;!x&&d.layers&&i<d.layers.length;i++)x=MM_findObj(n,d.layers[i].document);if(!x&&d.getElementById)x=d.getElementById(n);return x;}
function MM_swapImage(){var i,j=0,x,a=MM_swapImage.arguments;document.MM_sr=new Array;for(i=0;i<(a.length-2);i+=3)if((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x;if(!x.oSrc)x.oSrc=x.src;x.src=a[i+2];}}
function MM_openBrWindow(theURL,winName,features){window.open(theURL,winName,features);}
function MM_setTextOfLayer(objName,x,newText){if((obj=MM_findObj(objName))!=null)with(obj)if(document.layers){document.write(unescape(newText));document.close();}else innerHTML=unescape(newText);}
function MM_showHideLayers(){var i,p,v,obj,args=MM_showHideLayers.arguments;for(i=0;i<(args.length-2);i+=3)if((obj=MM_findObj(args[i]))!=null){v=args[i+2];if(obj.style){obj=obj.style;v=(v=='show')?'visible':(v=='hide')?'hidden':v;}obj.visibility=v;}}
function MM_displayStatusMsg(msgStr){status=msgStr;document.MM_returnValue=true;}
function MM_nbGroup(event,grpName){var i,img,nbArr,args=MM_nbGroup.arguments;if(event=="init"&&args.length>2){if((img=MM_findObj(args[2]))!=null&&!img.MM_init){img.MM_init=true;img.MM_up=args[3];img.MM_dn=img.src;if((nbArr=document[grpName])==null)nbArr=document[grpName]=new Array();nbArr[nbArr.length]=img;for(i=4;i<args.length-1;i+=2)if((img=MM_findObj(args[i]))!=null){if(!img.MM_up)img.MM_up=img.src;img.src=img.MM_dn=args[i+1];nbArr[nbArr.length]=img;}}}else if(event=="over"){document.MM_nbOver=nbArr=new Array();for(i=1;i<args.length-1;i+=3)if((img=MM_findObj(args[i]))!=null){if(!img.MM_up)img.MM_up=img.src;img.src=(img.MM_dn&&args[i+2])?args[i+2]:((args[i+1])?args[i+1]:img.MM_up);nbArr[nbArr.length]=img;}}else if(event=="out"){for(i=0;i<document.MM_nbOver.length;i++){img=document.MM_nbOver[i];img.src=(img.MM_dn)?img.MM_dn:img.MM_up;}}else if(event=="down"){nbArr=document[grpName];if(nbArr)for(i=0;i<nbArr.length;i++){img=nbArr[i];img.src=img.MM_up;img.MM_dn=0;}document[grpName]=nbArr=new Array();for(i=2;i<args.length-1;i+=2)if((img=MM_findObj(args[i]))!=null){if(!img.MM_up)img.MM_up=img.src;img.src=img.MM_dn=(args[i+1])?args[i+1]:img.MM_up;nbArr[nbArr.length]=img;}}}
function AC_AddExtension(src,ext){if(src.indexOf('?')!=-1)return src.replace(/\?/,ext+'?');else return src+ext;}
function AC_Generateobj(objAttrs,params,embedAttrs){var str='<object ';for(var i in objAttrs)str+=i+'="'+objAttrs[i]+'" ';str+='>';for(var i in params)str+='<param name="'+i+'" value="'+params[i]+'" /> ';str+='<embed ';for(var i in embedAttrs)str+=i+'="'+embedAttrs[i]+'" ';str+=' ></embed></object>';document.write(str);}
function AC_FL_RunContent(){var ret=AC_GetArgs(arguments,".swf","movie","clsid:d27cdb6e-ae6d-11cf-96b8-444553540000","application/x-shockwave-flash");AC_Generateobj(ret.objAttrs,ret.params,ret.embedAttrs);}
function AC_SW_RunContent(){var ret=AC_GetArgs(arguments,".dcr","src","clsid:166B1BCA-3F9C-11CF-8075-444553540000",null);AC_Generateobj(ret.objAttrs,ret.params,ret.embedAttrs);}
function AC_GetArgs(args,ext,srcParamName,classid,mimeType){var ret=new Object();ret.embedAttrs=new Object();ret.params=new Object();ret.objAttrs=new Object();for(var i=0;i<args.length;i=i+2){var currArg=args[i].toLowerCase();switch(currArg){case"classid":break;case"pluginspage":ret.embedAttrs[args[i]]=args[i+1];break;case"src":case"movie":args[i+1]=AC_AddExtension(args[i+1],ext);ret.embedAttrs["src"]=args[i+1];ret.params[srcParamName]=args[i+1];break;case"onafterupdate":case"onbeforeupdate":case"onblur":case"oncellchange":case"onclick":case"ondblClick":case"ondrag":case"ondragend":case"ondragenter":case"ondragleave":case"ondragover":case"ondrop":case"onfinish":case"onfocus":case"onhelp":case"onmousedown":case"onmouseup":case"onmouseover":case"onmousemove":case"onmouseout":case"onkeypress":case"onkeydown":case"onkeyup":case"onload":case"onlosecapture":case"onpropertychange":case"onreadystatechange":case"onrowsdelete":case"onrowenter":case"onrowexit":case"onrowsinserted":case"onstart":case"onscroll":case"onbeforeeditfocus":case"onactivate":case"onbeforedeactivate":case"ondeactivate":case"type":case"codebase":ret.objAttrs[args[i]]=args[i+1];break;case"width":case"height":case"align":case"vspace":case"hspace":case"class":case"title":case"accesskey":case"name":case"id":case"tabindex":ret.embedAttrs[args[i]]=ret.objAttrs[args[i]]=args[i+1];break;default:ret.embedAttrs[args[i]]=ret.params[args[i]]=args[i+1];}}ret.objAttrs["classid"]=classid;if(mimeType)ret.embedAttrs["type"]=mimeType;return ret;}
var isIE=(navigator.appVersion.indexOf("MSIE")!=-1)?true:false;var isWin=(navigator.appVersion.toLowerCase().indexOf("win")!=-1)?true:false;var isOpera=(navigator.userAgent.indexOf("Opera")!=-1)?true:false;function ControlVersion(){var version,axo,e;try{axo=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7");version=axo.GetVariable("$version");}catch(e){};if(!version){try{axo=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");version="WIN 6,0,21,0";axo.AllowScriptAccess="always";version=axo.GetVariable("$version");}catch(e){}};if(!version){try{axo=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3");version=axo.GetVariable("$version");}catch(e){}};if(!version){try{axo=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3");version="WIN 3,0,18,0";}catch(e){}};if(!version){try{axo=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");version="WIN 2,0,0,11";}catch(e){version=-1;}};return version;}
function GetSwfVer(){var flashVer=-1;if(navigator.plugins!=null&&navigator.plugins.length>0){if(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]){var swVer2=navigator.plugins["Shockwave Flash 2.0"]?" 2.0":"",flashDescription=navigator.plugins["Shockwave Flash"+swVer2].description,descArray=flashDescription.split(" "),tempArrayMajor=descArray[2].split("."),versionMajor=tempArrayMajor[0],versionMinor=tempArrayMajor[1],versionRevision=descArray[3];if(versionRevision=="")versionRevision=descArray[4];if(versionRevision[0]=="d")versionRevision=versionRevision.substring(1);else if(versionRevision[0]=="r"){versionRevision=versionRevision.substring(1);if(versionRevision.indexOf("d")>0){versionRevision=versionRevision.substring(0,versionRevision.indexOf("d"));}};var flashVer=versionMajor+"."+versionMinor+"."+versionRevision;}}else if(navigator.userAgent.toLowerCase().indexOf("webtv/2.6")!=-1)flashVer=4;else if(navigator.userAgent.toLowerCase().indexOf("webtv/2.5")!=-1)flashVer=3;else if(navigator.userAgent.toLowerCase().indexOf("webtv")!=-1)flashVer=2;else if(isIE&&isWin&&!isOpera){flashVer=ControlVersion()}return flashVer;}
function DetectFlashVer(reqMajorVer,reqMinorVer,reqRevision){versionStr=GetSwfVer();if(versionStr==-1){return false;}else if(versionStr!=0){if(isIE&&isWin&&!isOpera){tempArray=versionStr.split(" ");tempString=tempArray[1];versionArray=tempString.split(",");}else{versionArray=versionStr.split(".");}var versionMajor=versionArray[0],versionMinor=versionArray[1],versionRevision=versionArray[2];if(versionMajor>parseFloat(reqMajorVer)){return true;}else if(versionMajor==parseFloat(reqMajorVer)){if(versionMinor>parseFloat(reqMinorVer))return true;else if(versionMinor==parseFloat(reqMinorVer)){if(versionRevision>=parseFloat(reqRevision))return true;}}return false;}}
browserVersion();function initComm(){_comm.init();}var _comm=new Object({pi:null,st:null,ru:false,rs:0,pr:15000,init:function(){_comm.wake();addUnloadEvent(_comm.close);addMouseMoveEvent(_comm.wake);addKeyDownEvent(_comm.wake);},wake:function(){if(_comm.st)window.clearTimeout(_comm.st);_comm.st=window.setTimeout(_comm.sleep,30000);_comm.rs=2;if(_comm.ru==false){_comm.poll();_comm.pi=window.setInterval(_comm.poll,_comm.pr);_comm.ru=true;}},sleep:function(){if(_comm.pi)window.clearInterval(_comm.pi);_comm.rs=1;_comm.poll();_comm.pr=15000;_comm.ru=false;},close:function(){_comm.rs=0;_comm.poll();},poll:function(){var fv,js,sr,sd,ln,pv=0,m,r,q,g,b=document.documentElement;if(b)pv=(b.clientHeight+b.scrollTop)/b.scrollHeight;js=navigator&&navigator.javaEnabled()?true:false;if(self.screen){sr=screen.width+"x"+screen.height;sd=screen.colorDepth} else if(javaobj){try{var m=javaobj.getScreenSize();sr=m.width+"x"+m.height} catch(r){}}ln=(navigator&&navigator.browserLanguage?navigator.browserLanguage:(navigator&&navigator.language?navigator.language:"-")).toLowerCase();if(navigator&&navigator.plugins&&navigator.plugins['length']>0){for(m=0;m<navigator.plugins['length'];m++){r=navigator.plugins[m];if(r.name.indexOf("Shockwave Flash")>-1){fv=r.description.split("Shockwave Flash ")[1]}}}else if(window.ActiveXObject){for(q=10;q>=2;q--){try{g=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+q);if(g){fv=q+".0"}}catch(p){}}}else{fv="-"}if(_comm.rs==0)SystemAjaxFunctions.AjaxPoll(oRid,fv,js,sr,sd,ln,pv,0);else SystemAjaxFunctions.AjaxPoll(oRid,fv,js,sr,sd,ln,pv,_comm.rs,_comm.action);},action:function(r){eval(r.value)}})